name: 문서 배포

on:
  # 기본 브랜치인 "develop" 에 푸시할 때 마다 워크플로우 작동
  push:
    branches: [ "develop" ]
  
  workflow_dispatch:

# GitHub Pages 에 배포하기 위한 GITHUB_TOKEN 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write
  
# 동시성 배포 허용
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      # GitHub Pages 로 배포하기 위한 필수 설정
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-15  #최신버전
    steps:
    - name: 체크아웃 🛎️
      uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1 # xcode 버전 설정을 위함
      with:
        xcode-version: '16.0'
    - name: DocC 문서 빌드
      run: |
        swift package --allow-writing-to-directory ./docs \
        generate-documentation --target blog --disable-indexing \
        --output-path ./docs \
        --transform-for-static-hosting \
        --hosting-base-path swift-docc-blog
    - name: artifact 업로드
      uses: actions/upload-pages-artifact@v4
      with:
        # docs 경로에 있는 것만 업로드
        path: 'docs'
    - name: GitHub Pages 에 배포
      id: deployment
      uses: actions/deploy-pages@v4
